export type ValidSkills =
  | "Next.js"
  | "React"
  | "GraphQL"
  | "Nest.js"
  | "express.js"
  | "Node.js"
  | "MongoDB"
  | "Typescript"
  | "Javascript"
  | "HTML 5"
  | "CSS 3"
  | "React Native"
  | "Angular"
  | "Redux"
  | "Socket.io"
  | "Material UI"
  | "Tailwind CSS"
  | "AWS"
  | "Bootstrap"
  | "Google Auth"
  | "MySQL"
  | "Java"
  | "Databricks"
  | "Python"
  | "Docker"
  | "Kubernetes"
  | "PostgreSQL"
  | "Redis"
  | "Git"
  | "CI/CD"
  | "Jenkins"
  | "FastAPI"
  | "Django"
  | "Vue.js"
  | "Sass"
  | "Firebase"
  | "Azure"
  | "Google Cloud"
  | "Figma"
  | "Webpack"
  | "Jest"
  | "Cypress"
  | "Storybook"
  | "Prisma"
  | "Supabase"
  | "Vercel"
  | "Netlify"
  | "Three.js"
  | "WebGL"
  | "TensorFlow"
  | "PyTorch"
  | "Spring Boot"
  | "Laravel"
  | "PHP"
  | "Flutter"
  | "Dart"
  | "Flask"
  | "Django"
  | "FastAPI"
  | "SQL"
  | "NoSQL"
  | "Framer Motion"
  | "Next.js"
  | "React"
  | "TensorFlow"
  | "PyTorch"
  | "Framer Motion"
  | "BERT"
  | "DistilBERT"
  | "RoBERTa"
  | "Fine-tuning"
  | "LoRA"
  | "Gradio"
  | "SHAP"
  | "Lime"
  | "Streamlit"
  | "Hugging Face"
  | "Transformers"
  | "scikit-learn"
  | "Pandas"
  | "NumPy"
  | "Matplotlib"
  | "Seaborn"
  | "OpenCV"
  | "NLTK"
  | "spaCy"
  | "Next.js"
  | "React"
  | "spaCy"
  | "Power BI"
  | "Machine Learning"
  | "ARIMA"
  | "Time Series"
  | "Data Analysis"
  | "Statistics"
  | "Prophet"
  | "LSTM"
  | "A/B Testing"
  | "Data Visualization"
  | "Customer Segmentation"
  | "FAISS"
  | "RAG"
  | "NLP"
  | "Information Retrieval"
  | "Prompt Engineering"
  | "Plotly"
  | "SQLite"
  | "NLLB-200"
  | "PEFT"
  | "Optuna"
  | "SacreBLEU"
  | "COMET"
  | "chrF"
  | "Weights & Biases"
  | "GraphRAG"
  | "BM25"
  | "E5"
  | "Cross-encoder"
  | "Reranking"
  | "Bootstrap"
  | "Cohen's Kappa"
  | "VLM"
  | "Data Curation"
  | "Benchmarking"
  | "LaTeX"
  | "SLIDE";

export type ValidCategory =
  | "Full Stack"
  | "Frontend"
  | "Backend"
  | "UI/UX"
  | "Web Dev"
  | "Mobile Dev"
  | "3D Modeling"
  | "AI/ML"
  | "NLP"
  | "Research"
  | "Machine Translation"
  | "Petroleum-Domain MT"
  | "Mixture-of-Experts"
  | "Routing Diagnostics"
  | "LoRA / PEFT"
  | "Low-Resource NLP"
  | "Domain Adaptation"
  | "Data Quality"
  | "Hyperparameter Optimization"
  | "Human Evaluation"
  | "Evaluation"
  | "RAG"
  | "Information Retrieval"
  | "Responsible AI"
  | "Data-Centric ML"
  | "Shapley Attribution"
  | "Training Data"
  | "Technical Project";

export type ValidExpType =
  | "AI"
  | "Data Science"
  | "Research"
  | "Technical Project";

export type ValidPages =
  | "home"
  | "skills"
  | "projects"
  | "experience"
  | "contact"
  | "publications"
  | "resume";
