export type ValidSkills =
  | "Next.js"
  | "React"
  | "GraphQL"
  | "Nest.js"
  | "express.js"
  | "Node.js"
  | "MongoDB"
  | "Typescript"
  | "Javascript"
  | "HTML 5"
  | "CSS 3"
  | "React Native"
  | "Angular"
  | "Redux"
  | "Socket.io"
  | "Material UI"
  | "Tailwind CSS"
  | "AWS"
  | "Bootstrap"
  | "Google Auth"
  | "MySQL"
  | "Java"
  | "Databricks"
  | "Python"
  | "Docker"
  | "Kubernetes"
  | "PostgreSQL"
  | "Redis"
  | "Git"
  | "CI/CD"
  | "Jenkins"
  | "FastAPI"
  | "Django"
  | "Vue.js"
  | "Sass"
  | "Firebase"
  | "Azure"
  | "Google Cloud"
  | "Figma"
  | "Webpack"
  | "Jest"
  | "Cypress"
  | "Storybook"
  | "Prisma"
  | "Supabase"
  | "Vercel"
  | "Netlify"
  | "Three.js"
  | "WebGL"
  | "TensorFlow"
  | "PyTorch"
  | "Spring Boot"
  | "Laravel"
  | "PHP"
  | "Flutter"
  | "Dart"
  | "Flask"
  | "Django"
  | "FastAPI"
  | "SQL"
  | "NoSQL"
  | "Framer Motion"
  | "Next.js"
  | "React"
  | "TensorFlow"
  | "PyTorch"
  | "Framer Motion"
  | "BERT"
  | "DistilBERT"
  | "RoBERTa"
  | "Fine-tuning"
  | "LoRA"
  | "Gradio"
  | "SHAP"
  | "Lime"
  | "Streamlit"
  | "Hugging Face"
  | "Transformers"
  | "scikit-learn"
  | "Pandas"
  | "NumPy"
  | "Matplotlib"
  | "Seaborn"
  | "OpenCV"
  | "NLTK"
  | "spaCy"
  | "Next.js"
  | "React"
  | "spaCy"
  | "Power BI"
  | "Machine Learning"
  | "ARIMA"
  | "Time Series"
  | "Data Analysis"
  | "Statistics"
  | "Prophet"
  | "LSTM"
  | "A/B Testing"
  | "Data Visualization"
  | "Customer Segmentation"
  | "FAISS"
  | "RAG"
  | "NLP"
  | "Information Retrieval"
  | "Prompt Engineering"
  | "Plotly"
  | "SQLite";


export type ValidCategory =
  | "Full Stack"
  | "Frontend"
  | "Backend"
  | "UI/UX"
  | "Web Dev"
  | "Mobile Dev"
  | "3D Modeling"
  | "AI/ML"       
  | "NLP";         

export type ValidExpType = "AI" | "Data Science";

export type ValidPages =
  | "home"
  | "skills"
  | "projects"
  | "experience"
  | "contact"
  | "contributions"
  | "resume";
