export const siteConfig = {
  name: "Nordic AI Solutions | AI Developer & Consultant",
  authorName: "Jean Young",
  username: "Jean Young",
  description:
    "Jean Young's Nordic AI Solutions - AI developer and consultant specializing in machine learning, natural language processing, and intelligent automation. Offering both personal expertise and professional AI consulting services.",
  url: "https://nbarkiya.xyz",
  links: {
    twitter: "https://x.com/namanbarkiya",
    github: "https://github.com/Entropyobserver",
  },
  ogImage: "/profile-img.jpg",
  iconIco:
    "/favicon.ico",
  logoIcon:
    "/logo.png",
  keywords: [
    "Jean Young",
    "Nordic AI Solutions",
    "AI Developer",
    "AI Consultant",
    "Machine Learning Engineer",
    "NLP Developer",
    "AI Portfolio",
    "Next.js portfolio template",
    "React portfolio template",
    "Developer portfolio template",
    "Portfolio website template",
    "Next.js template",
    "Modern portfolio website",
    "AI Services",
    "Consulting Services",
    "Artificial Intelligence",
    "Open source portfolio template",
    "Web developer portfolio template",
    "Responsive portfolio template",
    "React.js portfolio",
    "Tailwind CSS portfolio",
    "Developer showcase template",
    "Free portfolio template",
    "Next.js 13 template",
    "Shadcn UI template",
    "Career timeline template",
    "Portfolio with dark mode",
    "GitHub portfolio template",
  ],
};
