export const siteConfig = {
  name: "Xiaojing Yang | AI & NLP Researcher | Machine Learning Engineer",
  authorName: "Xiaojing Yang",
  username: "Entropyobserver",
  description:
    "Xiaojing Yang is an AI and NLP researcher and machine learning engineer working across multilingual NLP, responsible AI, data-centric ML, and intelligent systems.",
  url: "https://nordic-ai.top",
  links: {
    twitter: "https://x.com/Entropyobserver",
    github: "https://github.com/Entropyobserver",
  },
  ogImage: "/profile-avatar.png",
  iconIco:
    "/favicon.ico",
  logoIcon:
    "/logo.png",
  keywords: [
    "Xiaojing Yang",
    "Nordic AI Solutions",
    "AI Researcher",
    "NLP Researcher",
    "Machine Learning Engineer",
    "NLP",
    "Responsible AI",
    "Data-Centric ML",
    "Intelligent Systems",
    "AI Portfolio",
    "Next.js portfolio template",
    "React portfolio template",
    "Developer portfolio template",
    "Portfolio website template",
    "Next.js template",
    "Modern portfolio website",
    "AI Services",
    "Consulting Services",
    "Artificial Intelligence",
    "Open source portfolio template",
    "Web developer portfolio template",
    "Responsive portfolio template",
    "React.js portfolio",
    "Tailwind CSS portfolio",
    "Developer showcase template",
    "Free portfolio template",
    "Next.js 13 template",
    "Shadcn UI template",
    "Career timeline template",
    "Portfolio with dark mode",
    "GitHub portfolio template",
  ],
};
